// Replica templates built using the custom template system.
// These demonstrate that the box/department-area model can exactly reproduce
// the built-in template configs using only CustomFlyerTemplateConfig data structures.
// No background images — built entirely from colored boxes and department areas.
import type { CustomFlyerTemplateConfig } from "./loadFlyerTemplateConfig";

const FONT = "Anton, Impact, sans-serif";
const WHITE = "#ffffff";

/** From-scratch replica of weekly_v2 using only boxes + department areas on a white canvas */
export const WEEKLY_V2_REPLICA: CustomFlyerTemplateConfig = {
  templateId: "custom_replica_weekly_v2",
  isCustom: true,
  name: "Weekly v2 (Replica)",
  pages: [
    // ── Page 1: Hot Sale ──────────────────────────────────────────────
    {
      pageId: "p1",
      canvasWidth: 1650,
      canvasHeight: 2516,
      backgroundColor: "#ffffff",
      boxes: [
        {
          id: "v2_p1_header",
          label: "HOT SALE 热卖",
          departmentKey: "hot_sale",
          boxType: "product",
          color: "#8B3A3A",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 96,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 0, width: 1650, height: 674,
          rows: 0,
        },
      ],
      departmentAreas: [
        {
          id: "hot_sale_p1",
          departmentKey: "hot_sale",
          label: "Hot Sale",
          rows: 5,
          productRegion: { x: 0, y: 674, width: 1650, height: 1842 },
        },
      ],
    },
    // ── Page 2: Grocery ───────────────────────────────────────────────
    {
      pageId: "p2",
      canvasWidth: 1650,
      canvasHeight: 2516,
      backgroundColor: "#ffffff",
      boxes: [
        {
          id: "v2_p2_header",
          label: "GROCERY 杂货",
          departmentKey: "grocery",
          boxType: "product",
          color: "#D4A017",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 48,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 0, width: 1650, height: 83,
          rows: 0,
        },
      ],
      departmentAreas: [
        {
          id: "grocery_p2",
          departmentKey: "grocery",
          label: "Grocery",
          rows: 5,
          productRegion: { x: 0, y: 83, width: 1650, height: 2425 },
        },
      ],
    },
    // ── Page 3: Produce + Hot Food ────────────────────────────────────
    {
      pageId: "p3",
      canvasWidth: 1650,
      canvasHeight: 2516,
      backgroundColor: "#ffffff",
      boxes: [
        {
          id: "v2_p3_produce_header",
          label: "PRODUCE 生鲜蔬果",
          departmentKey: "produce",
          boxType: "product",
          color: "#00944C",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 48,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 0, width: 1650, height: 83,
          rows: 0,
        },
        {
          id: "v2_p3_hotfood_divider",
          label: "HOT FOOD 熟食",
          departmentKey: "hot_food",
          boxType: "product",
          color: "#E05020",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 36,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 1823, width: 1650, height: 57,
          rows: 0,
        },
      ],
      departmentAreas: [
        {
          id: "produce_p3",
          departmentKey: "produce",
          label: "Produce",
          rows: 4,
          productRegion: { x: 0, y: 83, width: 1650, height: 1740 },
        },
        {
          id: "hot_food_p3",
          departmentKey: "hot_food",
          label: "Hot Food",
          rows: 2,
          productRegion: { x: 0, y: 1880, width: 1650, height: 635 },
        },
      ],
    },
    // ── Page 4: Meat + Frozen + Seafood ──────────────────────────────
    {
      pageId: "p4",
      canvasWidth: 1650,
      canvasHeight: 2516,
      backgroundColor: "#ffffff",
      boxes: [
        {
          id: "v2_p4_meat_header",
          label: "MEAT 肉类",
          departmentKey: "meat",
          boxType: "product",
          color: "#8B3A22",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 72,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 0, width: 1650, height: 319,
          rows: 0,
        },
        {
          id: "v2_p4_frozen_divider",
          label: "FROZEN 冷冻食品",
          departmentKey: "frozen",
          boxType: "product",
          color: "#1A8A88",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 36,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 923, width: 1650, height: 60,
          rows: 0,
        },
        {
          id: "v2_p4_seafood_divider",
          label: "SEAFOOD 海鲜",
          departmentKey: "seafood",
          boxType: "product",
          color: "#1E4D7B",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 36,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 1977, width: 1650, height: 71,
          rows: 0,
        },
      ],
      departmentAreas: [
        {
          id: "meat_p4",
          departmentKey: "meat",
          label: "Meat",
          rows: 2,
          productRegion: { x: 0, y: 319, width: 1650, height: 604 },
        },
        {
          id: "frozen_p4",
          departmentKey: "frozen",
          label: "Frozen",
          rows: 3,
          productRegion: { x: 0, y: 983, width: 1650, height: 994 },
        },
        {
          id: "seafood_p4",
          departmentKey: "seafood",
          label: "Seafood",
          rows: 1,
          productRegion: { x: 0, y: 2048, width: 1650, height: 462 },
        },
      ],
    },
  ],
};

/** From-scratch replica of weekly_v1 using only boxes + department areas on a white canvas */
export const WEEKLY_V1_REPLICA: CustomFlyerTemplateConfig = {
  templateId: "custom_replica_weekly_v1",
  isCustom: true,
  name: "Weekly v1 (Replica)",
  pages: [
    // ── Page 1: Grocery ───────────────────────────────────────────────
    {
      pageId: "p1",
      canvasWidth: 1650,
      canvasHeight: 2513,
      backgroundColor: "#ffffff",
      boxes: [
        {
          id: "v1_p1_banner",
          label: "",
          departmentKey: "grocery",
          boxType: "color",
          color: "#D4A017",
          textColor: WHITE,
          x: 0, y: 0, width: 1650, height: 420,
          rows: 0,
        },
        {
          id: "v1_p1_grocery_label",
          label: "GROCERY 杂货",
          departmentKey: "grocery",
          boxType: "product",
          color: "#2E7D32",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 28,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 420, width: 1650, height: 42,
          rows: 0,
        },
      ],
      departmentAreas: [
        {
          id: "grocery_p1",
          departmentKey: "grocery",
          label: "Grocery",
          rows: 8,
          productRegion: { x: 39, y: 462, width: 1572, height: 2051 },
        },
      ],
    },
    // ── Page 2: Frozen + Hot Food + Sushi ────────────────────────────
    {
      pageId: "p2",
      canvasWidth: 1650,
      canvasHeight: 2513,
      backgroundColor: "#ffffff",
      boxes: [
        {
          id: "v1_p2_frozen_header",
          label: "FROZEN 冷冻食品",
          departmentKey: "frozen",
          boxType: "product",
          color: "#1A8A88",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 32,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 0, width: 1650, height: 53,
          rows: 0,
        },
        {
          id: "v1_p2_hotfood_divider",
          label: "HOT FOOD 熟食",
          departmentKey: "hot_food",
          boxType: "product",
          color: "#E05020",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 48,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 937, width: 1650, height: 85,
          rows: 0,
        },
        {
          id: "v1_p2_sushi_divider",
          label: "SUSHI 寿司",
          departmentKey: "sushi",
          boxType: "product",
          color: "#C06080",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 42,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 1799, width: 1650, height: 76,
          rows: 0,
        },
      ],
      departmentAreas: [
        {
          id: "frozen_p2",
          departmentKey: "frozen",
          label: "Frozen",
          rows: 3,
          productRegion: { x: 39, y: 53, width: 1572, height: 884 },
        },
        {
          id: "hot_food_p2",
          departmentKey: "hot_food",
          label: "Hot Food",
          rows: 3,
          productRegion: { x: 39, y: 1022, width: 1572, height: 777 },
        },
        {
          id: "sushi_p2",
          departmentKey: "sushi",
          label: "Sushi",
          rows: 2,
          productRegion: { x: 39, y: 1875, width: 1572, height: 591 },
        },
      ],
    },
    // ── Page 3: Meat + Vegetable + Fruit + Seafood ───────────────────
    {
      pageId: "p3",
      canvasWidth: 1650,
      canvasHeight: 2513,
      backgroundColor: "#ffffff",
      boxes: [
        {
          id: "v1_p3_meat_header",
          label: "MEAT 肉类",
          departmentKey: "meat",
          boxType: "product",
          color: "#8B3A22",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 32,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 0, width: 1650, height: 53,
          rows: 0,
        },
        {
          id: "v1_p3_veg_divider",
          label: "VEGETABLE 蔬菜",
          departmentKey: "vegetable",
          boxType: "product",
          color: "#2E7D32",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 32,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 745, width: 1650, height: 57,
          rows: 0,
        },
        {
          id: "v1_p3_fruit_divider",
          label: "FRUIT 水果",
          departmentKey: "fruit",
          boxType: "product",
          color: "#D2522A",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 32,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 1298, width: 1650, height: 53,
          rows: 0,
        },
        {
          id: "v1_p3_seafood_divider",
          label: "SEAFOOD 海鲜",
          departmentKey: "seafood",
          boxType: "product",
          color: "#1E4D7B",
          textColor: WHITE,
          fontFamily: FONT,
          fontSize: 48,
          textAlign: "center",
          textVertical: "middle",
          x: 0, y: 1920, width: 1650, height: 88,
          rows: 0,
        },
      ],
      departmentAreas: [
        {
          id: "meat_p3",
          departmentKey: "meat",
          label: "Meat",
          rows: 3,
          productRegion: { x: 39, y: 53, width: 1572, height: 692 },
        },
        {
          id: "vegetable_p3",
          departmentKey: "vegetable",
          label: "Vegetable",
          rows: 2,
          productRegion: { x: 39, y: 802, width: 1572, height: 496 },
        },
        {
          id: "fruit_p3",
          departmentKey: "fruit",
          label: "Fruit",
          rows: 2,
          productRegion: { x: 39, y: 1351, width: 1572, height: 569 },
        },
        {
          id: "seafood_p3",
          departmentKey: "seafood",
          label: "Seafood",
          rows: 2,
          productRegion: { x: 39, y: 2008, width: 1572, height: 455 },
        },
      ],
    },
  ],
};

export const ALL_REPLICAS = [WEEKLY_V2_REPLICA, WEEKLY_V1_REPLICA];
